admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /adminarea

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /adminarea

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /adminarea

md5:
    resource: "@MD5BusterBundle/Resources/config/routing.yml"
    prefix:   /