security:
    providers:
        in_memory:
            memory: ~

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)/
            security: false
        md5buster_site_area:
            pattern: ^/
            anonymous:  ~
    access_control:
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }